config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :equipments do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [] do
    member { patch :update_rating }
    member { patch :accept }
    member { patch :deny }
    member { patch :cancel }
  end
  resource :account, only: [:show]

  get "categories", to: "pages#categories"
  get "dashboard", to: "pages#dashboard"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :equipment
  validates :start_date, :end_date, presence: true
  validate :end_date_after_start_date
  validate :end_of_start_date_not_in_the_past

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    errors.add(:end_date, "must be after the start date") if end_date < start_date
  end

  def end_of_start_date_not_in_the_past
    return if end_date.blank? || start_date.blank?

    errors.add(:start_date, "cannot be in the past") if start_date < Date.today
  end
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo
  validates :title, presence: true
  validates :description, presence: true
  validates :address, presence: true
  validates :daily_price, presence: true
  validates :sport_category, presence: true, inclusion: { in: ApplicationController::SPORT_CATEGORIES }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  SPORT_CATEGORIES = ['Ski', 'Snowboard', 'Kite Surf', 'Snowkite', 'Wingsuit', 'Highline']
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!

  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # def user_not_authorized
  #  flash[:alert] = "You are not authorized to perform this action."
  #  redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/

  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :avatar])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])

  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_equipment, only: [:new, :create]
  before_action :find_booking, only: [:accept, :deny]
  def new
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    authorize @booking
    @booking.user = current_user
    @booking.equipment = @equipment
    if @booking.save
      flash.notice = "Booking created !"
      redirect_to equipment_path(@equipment)
    else
      render :new
    end
  end

  def show
    authorize @booking
  end

  def accept
    render json: { status: false } and return unless @booking.status == "pending"

    authorize @booking
    @booking.status = "accepted"
    is_booking_saved = @booking.save
    render json: { status: is_booking_saved, type: "Accepted" }
  end

  def deny
    render json: { status: false } and return unless @booking.status == "pending"

    authorize @booking
    @booking.status = "denied"
    @booking.save
    is_booking_saved = @booking.save
    render json: { status: is_booking_saved, type: "Denied" }
  end

  private

  def find_equipment
    @equipment = Equipment.find(params[:equipment_id])
  end

  def find_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/equipments_controller.rb
class EquipmentsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :find_equipment, only: [:edit, :show, :update, :destroy]

  def index
    if params[:category]
      @equipments = policy_scope(Equipment.where(sport_category: params[:category]))
      @category = params[:category]
    else
      @category = "all"
      @equipments = policy_scope(Equipment)
    end
    @markers = @equipments.geocoded.map do |equipment|
      {
        lat: equipment.latitude,
        lng: equipment.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { equipment: equipment }),
        image_url: helpers.asset_url('logo.png'),
        id: equipment.id
      }
    end
  end

  def new
    @equipment = Equipment.new
    authorize @equipment
  end

  def create
    @equipment = Equipment.new(equipment_params)
    authorize @equipment
    @equipment.user = current_user
    if @equipment.save
      redirect_to equipment_path(@equipment)
    else
      render :new
    end
  end

  def edit
  end

  def show
    authorize @equipment
  end

  def update
  end

  def destroy
    @equipment.destroy
    redirect_to equipments_path
  end

  private

  def find_equipment
    @equipment = Equipment.find(params[:id])
    authorize @equipment
  end

  def equipment_params
    params.require(:equipment)
          .permit([:title, :description, :address, :daily_price, :sport_category, :photo])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :categories]
  
  def home
  end

  def dashboard
    @bookings = policy_scope(Booking.where(user_id: current_user))
    @equipments = policy_scope(Equipment.where(user_id: current_user))
  end

  def categories
    @categories = ApplicationController::SPORT_CATEGORIES
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="d-flex justify-content-center mt-10">
  <%= simple_form_for [@equipment, @booking] do |f| %>
    <%= f.input  :start_date, as: :hidden, input_html: {id: "range_start", style: "display: none;"} %>
    <%= f.input  :end_date, as: :hidden, input_html: {id: "range_end"}%>
    <%= f.submit  class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/equipments/_info_window.html.erb
<div class="container rounded">
  <h5><strong><%= link_to equipment.title, equipment_path(equipment) %></strong></h5>
  <% if equipment.photo.attached? %>
        <%= cl_image_tag equipment.photo.key, height: 120, width: 120 %>
    <% else %>
      <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg", style="width: 120px; height: 120px;"/>
    <% end %>
  <div>
  <br>
    <p>Rent it for: <strong><%= equipment.daily_price %>€ /day</strong></p>
    <p>Owner: <strong><%= equipment.user.first_name %></strong> 😛</p>
  </div>
</div>

app/views/equipments/index.html.erb
<div class="container mt-4">
  <!-- browse buttons -->
  <div class="d-flex justify-content-around">
    <% unless @category == "all" %>
      <%= link_to "All", equipments_path, class: 'btn btn-ghost' %>
    <% end %>
    <% ApplicationController::SPORT_CATEGORIES.each do |sport_category| %>
      <%= link_to sport_category, equipments_path(category: sport_category), class: "btn btn-ghost#{'-selected' if params[:category] == sport_category}" %>
    <% end %>
  </div>
  <h3 class="mt-4 mb-2 ml-3" id="index_title"><%= @category.capitalize %> kits available to rent: </h3>
  <div class="container">
    <div class="row">
    <div class="col-4">
      <% @equipments.each do |equipment| %>
        <div class="card-product mt-2" data-equipment-id="<%= equipment.id %>">
          <% if equipment.photo.attached? %>
            <%= cl_image_tag equipment.photo.key %>
          <% else %>
            <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
          <% end %>

          <div class="card-product-infos">
            <h2><%= link_to equipment.title, equipment_path(equipment) %></h2>
            <p><%= equipment.description %></p>
          </div>
        </div>
      <% end %>
    </div>
    <!-- map -->
    <div id="map"
        class="col-8 mt-2"
        style="width: 100%; height: 600px; position: sticky; top: 75px"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
  </div>
</div>

app/views/equipments/new.html.erb
<div class="container">
  <%= simple_form_for @equipment, url: equipments_path do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :address %>
    <%= f.input :daily_price %>
    <%= f.input :sport_category, collection: ApplicationController::SPORT_CATEGORIES %>
    <%= f.input :photo, as: :file %>
    <%= f.submit %>
  <% end %>
</div>

app/views/equipments/show.html.erb
<div class="container mx-20 mt-4">
  <div class="d-flex flex-row justify-content-around">
    <div class="d-flex inline" >
      <div class="mr-4">
        <h2 class="mt-1 w-100"><%= @equipment.title %>  </h2>
        <div class="card-equipment">
          <% if @equipment.photo.attached? %>
            <%= cl_image_tag @equipment.photo.key, height: 300, width: 400 %>
          <% else %>
            <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
          <% end %>
          <div class="card-equipment-infos">
            <div>
              <p><i class="far fa-file-alt mr-2"></i><%= @equipment.description %></p>
              <p><i class="fas fa-map-marked-alt mr-2"></i><%= @equipment.address %></p>
              <p><i class="fas fa-tag mr-2"></i><%= @equipment.sport_category %></p>
            </div>
            <h2 class="card-equipment-pricing"><%= @equipment.daily_price %>€/day</h2>
            <% if @equipment.user.avatar.attached?  %>
              <img class="card-equipment-user avatar-bordered" src="<%= cl_image_path @equipment.user.avatar.key, height: 300, width: 300,  crop: :fill %>" border-radius= 50px />
            <% else %>
              <img class="card-equipment-user avatar-bordered" src="https://creai-grand-est.fr/bundles/admin/images/user-empty-avatar.png"/>
            <% end %>
          </div>
        </div>
      </div>
    </div>
      <div class="d-flex inline calendar">
        <%= simple_form_for [@equipment, Booking.new] do |f| %>
          <%= f.input :start_date, as: :hidden, input_html: {id: "range_start", style: "display: none;"} %>
          <%= f.input :end_date, as: :hidden, input_html: {id: "range_end"}%>
          <%= f.submit class: 'btn btn-primary btn-block' %>
        <% end %>
      </div>
</div>




<% if policy(@equipment).edit? %>
      <%= link_to "Update", edit_equipment_path(@equipment) %>
    <% end %>

    <p><% if policy(@equipment).destroy? %>
      <%= link_to  @equipment, method: :delete, data: { confirm: 'Are you sure?'} do %>
        <i class="fa fa-trash"></i>
      <% end %>
    <% end %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>XtremeSportsRental</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <% if current_page?('/') %>
      <div class="custom-container" style="padding-top: 0 !important">
    <% else %>
      <div class="custom-container">
    <% end %>
    <%= yield %>
    </div>
    </div>
    <%= render 'shared/flashes' %>
    <% unless current_page?("/") %>
      <%= render 'shared/footer' %>
    <% end %>
  </body>
</html>

app/views/pages/categories.html.erb
<div class="container">

<div class="cards">
  <%= link_to equipments_path(category:"Ski") do %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://img4.onthesnow.com/image/la/92/92811.jpg)">
      <span>Ski</span>
    </div>
  <% end %>
  <%= link_to equipments_path(category:"Snowboard") do %>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.cdn.snowleader.com/media/catalog/category/jones-banniere_1.jpg)">
    Snowboard
  </div>
  <% end %>
  <%= link_to equipments_path(category:"Kite Surf") do %>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.camping-castors.fr/wp-content/uploads/kitesurf-calvi.jpg)">
    Kite Surf
  </div>
  <% end %>

  <%= link_to  equipments_path(category:"Snowkite") do %>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.ohbox.ch/media/catalog/product/cache/2/image/9df78eab33525d08d6e5fb8d27136e95/q/8/q8a3007-1600x1066.jpg)">
    Snowkite
  </div>
  <% end %>

  <%= link_to equipments_path(category:"Wingsuit") do %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://adventuresportsjournal.com/wp-content/uploads/2012/04/SZ-07Gap-WS-LJA-01-1.jpg)">
      Wingsuit
    </div>
  <% end %>
  <%= link_to equipments_path(category:"Highline") do %>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://i.pinimg.com/originals/92/f4/40/92f4409a77485dd19972870aba177d18.jpg)">
    Highline
  </div>
  <% end %>
</div>

app/views/pages/dashboard.html.erb
<%
  profile_tab = params[:tab] == "profile" || !params[:tab].present?
  bookings_tab = params[:tab] == "bookings"
  equipment_tab = params[:tab] == "equipment"
%>

<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link <%= "active" if profile_tab %>" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="<%= profile_tab %>">Profile</a>
  </li>
  <li class="nav-item">
    <a class="nav-link <%= "active" if bookings_tab %>" id="my_bookings-tab" data-toggle="tab" href="#my_bookings" role="tab" aria-controls="my_bookings" aria-selected="<%= bookings_tab %>">My Bookings</a>
  </li>
  <li class="nav-item">
    <a class="nav-link <%= "active" if equipment_tab %>" id="my_equipment-tab" data-toggle="tab" href="#my_equipment" role="tab" aria-controls="my_equipment" aria-selected="<%= bookings_tab %>">My equipment</a>
  </li>
</ul>

<div class="tab-content" id="myTabContent">

  <div class="tab-pane fade <%= "show active" if profile_tab %> mt-5" id="profile" role="tabpanel" aria-labelledby="profile-tab">

    <div class="row px-30 col-8 d-flex space-between">
      <div class="card mt-2 ml-4 px-30">
        <div class="col-10">

          <div class="card-photo pl-3 pt-3">
            <% if current_user.avatar.attached?  %>
              <img class="profile-picture" src="<%= cl_image_path current_user.avatar.key, height: 150, width: 150,  crop: :fill %>"/>
            <% else %>
              <img class="avatar" src="https://creai-grand-est.fr/bundles/admin/images/user-empty-avatar.png"/>
            <% end %>
          </div>

          <div class="card-body">
            <h5 class="card-title"><%= @current_user.first_name %> <%= @current_user.last_name %></h5>
          </div>

        </div>

        <div class="col-10">
          <p class="card-text pl-3"><%= @current_user.bio %>Hi everybody, I am 39 years old, passionate about mountain and puff since my youngest age. I love above all sharing tips and meeting awesome people. Feel free to get in touch!
          See y'all on the slopes</p> <!-- static bio -->
        </div>

        <div class="col-10">

          <ul class="list-group list-group-flush">
            <li class="list-group-item">Favorite sport:<i class="fas fa-skiing"></i>
            <% @categories = [] %>
            <% @equipments.each do |equipment| %>
                <% @categories.push(equipment.sport_category) %>
            <% end %>
            <br>
            <% @categories = @categories.uniq %>
            <% @categories.each do |cat| %>
              <%= cat %>
            <% end %>
            </li>
            <li class="list-group-item">Spot:<i class="fas fa-mountain"></i>
            <!-- Fav spot => adress -->
            </li>
          </ul>

        </div>

      </div>
    </div>
  </div>

  <!-- Bookings -->

  <div class="container tab-pane fade <%= "show active" if bookings_tab %> mt-5" id="my_bookings" role="tabpanel" aria-labelledby="my_bookings-tab">
    <h1 class="mt-2 ml-4">My Bookings</h1>

    <% @bookings.each do |booking| %>

    <div class="container">
      <div class="row">

        <div class="card-product mt-2 ml-4 col-6">

          <% if booking.equipment.photo.attached? %>
            <%= cl_image_tag booking.equipment.photo.key %>
          <% else %>
            <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
          <% end %>

          <div class="card-product-infos">
            <h2><%= booking.equipment.title %></h2>
            <p><%= booking.equipment.description %></p>
            <p><strong>Start date </strong><%= booking.start_date.day %>/<%= booking.start_date.month %>/<%= booking.start_date.year %></p>
            <p><strong>Duration: </strong><%= (booking.end_date - booking.start_date).to_i/(3600*24) %> days</p>
          </div>
        </div>

        <div class="card-product mt-2 ml-4 col-4">
          <div class="card-product-infos">
            <p><strong><%= booking.equipment.daily_price %>€ / day</strong></p>
            <br>
            <p><strong>Total price: </strong><%= (booking.end_date - booking.start_date).to_i/(3600*24) * booking.equipment.daily_price %> €</p>
            <p><strong>Status: </strong><span data-update-status-target="status"><%= booking.status.capitalize %></span></p>
          </div>
        </div>

      </div>
    </div>

    <% end %>

  </div>

   <!-- Equipment -->


  <div class="container tab-pane fade <%= "show active" if equipment_tab %> mt-5" id="my_equipment" role="tabpanel" aria-labelledby="my_equipment-tab">

    <h3 class="mt-4 mb-2 ml-4"> My equipment: </h3>

    <% @equipments.each do |equipment| %>
        <div class="card-product mt-2 ml-4">
          <% if equipment.photo.attached? %>
            <%= cl_image_tag equipment.photo.key %>
          <% else %>
            <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
          <% end %>

          <div class="card-product-infos flex-grow-1">
            <h2><%= link_to equipment.title, equipment_path(equipment) %></h2>
            <p><%= equipment.description %></p>
          </div>
          <button class="btn btn-sm btn-primary mr-4" type="button" data-toggle="collapse" data-target="#collapseExample-<%= equipment.id %>" aria-expanded="false" aria-controls="collapseExample-<%= equipment.id %>">
            View bookings
          </button>
        </div>
        <div class="collapse ml-2" id="collapseExample-<%= equipment.id %>">
            <div class="card-product card-body ml-4 border-top" data-controller="update-status">
              <ul>
                <% equipment.bookings.each do |booking| %>
                  <li class="d-flex align-items-center justify-content-between mt-1">
                    <div class="flex-grow-1">
                      <strong>Booker </strong>
                      <%= booking.user.first_name%> <%= booking.user.last_name %> -
                      <strong>Start date </strong>
                       <%= booking.start_date.day %>/<%= booking.start_date.month %>/<%= booking.start_date.year %> -
                      <strong>Duration: </strong>
                      <%= (booking.end_date - booking.start_date).to_i/(3600*24) %> days -
                      <strong>Total price: </strong>
                      <%= (booking.end_date - booking.start_date).to_i/(3600*24) * equipment.daily_price %> € -
                      <strong>Status: </strong>
                      <span data-update-status-target="status"><%= booking.status.capitalize %></span>
                    </div>
                    <% if booking.status == "pending" %>
                    <div
                      class="ml-2 btn btn-sm btn-primary"
                      data-update-status-target="acceptButton"
                      data-url="<%= accept_booking_path(booking) %>"
                      data-action="click->update-status#update">
                      Accept
                    </div>
                    <div
                      class="ml-2 btn btn-sm btn-primary"
                      data-update-status-target="denyButton"
                      data-url="<%= deny_booking_path(booking) %>"
                      data-action="click->update-status#update">
                      Deny
                    </div>

                    <% end %>

                    </li>
                <% end %>
              </ul>
            </div>
          </div>

    <% end %>

  </div>
</div>

app/views/pages/home.html.erb
<header>
  <div class="overlay"></div>
  <video playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop">
    <source src="https://res.cloudinary.com/dorboeznn/video/upload/v1613661994/video%20Nico/Xtrem_Snowboard_wryqu1.mp4" type="video/mp4">
  </video>
  <div class="container h-100">
    <div class="d-flex h-100 text-center align-items-center">
      <div class="w-100 text-white">
        <h1 class="display-3">Xtreme Sports NICOLAS 😬</h1>
        <p class="lead mb-0">Live on the edge & access the latest kit from fellow riders.</p>
        <br>
        <%= link_to "Experience Now", categories_path, class: 'btn btn-light btn-lg', id:'homebtncolor' %>
      </div>
    </div>
  </div>
</header>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Xtreme Sports
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon <% if current_page?("/") %> home-navbar <% end %> <% unless current_page?("/") %> white-navbar <% end %>">
  <%= link_to "/", class: "navbar-brand" do %>
        <%= image_tag "https://res.cloudinary.com/dcj85wvte/image/upload/v1613468890/logo_size_ce3zg1.jpg" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <% if policy(Equipment).show? %>
          <%= link_to "Find cool gear", equipments_path(), class: "nav-link" %>
        <% end %>
      </li>
      <li class="nav-item">
        <% if policy(Equipment).create? %>
          <%= link_to "Share my gear", new_equipment_path(), class: "nav-link" %>
        <% end %>
      </li>

      <!-- <li><%=  current_user.first_name if user_signed_in? %></li> -->

      <li class="nav-item dropdown">
        <% if user_signed_in? && current_user.avatar.attached?  %>
          <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="<%= cl_image_path current_user.avatar.key, height: 300, width: 300, crop: :fill %>" />
        <% else %>
          <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://creai-grand-est.fr/bundles/admin/images/user-empty-avatar.png" />
        <% end %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Profile", "/dashboard?tab=profile", class: "dropdown-item" %>
          <%= link_to "Bookings", "/dashboard?tab=bookings", class: "dropdown-item" %>
          <%= link_to "Equipment", "/dashboard?tab=equipment", class: "dropdown-item" %>
          <% if user_signed_in? %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            <% else %>
            <%= link_to "Login", new_user_session_path, class: "dropdown-item" %>
          <% end %>

          </div>
      </li>
    </ul>
  </div>
</div>